---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```
# pharmaprepro

This package is for medical staff such as pharmacists to use for preprocessing clinical data.

## Installation

You can install the released version of pharmaprepro from [GitHub](https://github.com/nyubachi/pharmaprepro) with:

``` r
install.packages("devtools")
require(devtools)
install_github("nyubachi/pharmaprepro")
```

## Example

```{r}
# loading package
library(pharmaprepro)
```

```{r}
# test data
x <- data.frame(age = c(109, 98, 47, 25),
                height = c(161.5, 182.5, 170.1, 155.4),
                weight = c(55.2, 70.2, 60.5, 54.8),
                scr = c(0.8, 1.2, 0.4, 0.5),
                gender = c("female", "male", "male", "female"),
                birthday = c("M43.09.12", "T10.11.05", "S47.03.31", "H06.12.29"))
```

### bmicalc

```{r}
bmicalc(x$height, x$weight)
```

### ccrcalc

If scr is less than 0.6, it rounds up to 0.6.
```{r}
ccrcalc(x$age, x$weight, x$scr, x$gender, 1)
```

No scr correction.
```{r}
ccrcalc(x$age, x$weight, x$scr, x$gender, 0)
```

### stdwtcalc

```{r}
stdwtcalc(x$height)
```

### wareki2seireki

```{r}
wareki2seireki(x$birthday)
```
